### ISSUE TITLE
Extension “keyboard-reset@galets” does not exist

### ISSUE THREAD

**Issue by jadeye** [galets/gnome-keyboard-reset#1]
Ubuntu 22.04 fresh install:
`$ make install

install -d ~/.local/share/gnome-shell/extensions/keyboard-reset@galets
cp -a metadata.json extension.js ~/.local/share/gnome-shell/extensions/keyboard-reset@galets/
$ gnome-extensions enable keyboard-reset@galets
**Gives Nothing**

$ sudo gnome-extensions enable keyboard-reset@galets
(gnome-extensions enable:251399): dconf-WARNING **: 21:17:39.786: failed to commit changes to dconf: Failed to execute child process “dbus-launch” (No such file or directory)`

Can you help please?

**Comment by galets** [comment]
- what's your gnome version?
- did you try enabling extensions in extension manager? https://github.com/mjakeman/extension-manager

**Comment by galets** [comment]
closing this issue due to no response

**Comment by kristevalex** [comment]
Had a similar issue, in the end PC restart helped, maybe restarting shell it's enough or I did something wrong
