### ISSUE TITLE
Gnome 47 released

### ISSUE THREAD

**Issue by Serg-VL** [galets/gnome-keyboard-reset#10]
Extension marked incompatible %(

**Comment by galets** [comment]
I suspect, this is just a manifest fix. I don't have gnome 47 installed, so I cannot readily test that. Do you mind testing it for me? Here are the steps:

```bash
git clone https://github.com/galets/gnome-keyboard-reset
cd gnome-keyboard-reset
git checkout test-gnome-37
make install
```

**Comment by Serg-VL** [comment]
It's working!

**Comment by galets** [comment]
pull req  #11
