### ISSUE TITLE
Compatibility with Ubuntu 24.04 LTS and GNOME 46

### ISSUE THREAD

**Issue by KallistoD** [galets/gnome-keyboard-reset#2]
Tried the extension on Ubuntu 24.04 LTS (X11 / GNOME 46).

Extension Manager does not allow to enable the extension due to version incompatibility. So, I modified the file:
`~/.local/share/gnome-shell/extensions/keyboard-reset@galetsmetadata.json`
to include versions 45 and 46 in the line:
`"shell-version": ["41", "42", "43", "44", "45", "46"],`

Then, Extension Manager shows the error message:
`SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/misc/extensionUtils.js:4:0`

Any ideas why it does not work and how to fix it, please?

**Comment by galets** [comment]
In order to use extension in gnome 45+, code needs to be refactored as per: https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by galets** [comment]
@KallistoD can you please test following branch: https://github.com/galets/gnome-keyboard-reset/tree/u2204 as such:

```bash
git clone https://github.com/galets/gnome-keyboard-reset
cd gnome-keyboard-reset
git checkout u2204
make install
```

**Comment by KallistoD** [comment]
Just tried the branch u2204. It works for me as expected: The extension is loaded by GNOME without any errors and switches to the default keyboard layout on the lock screen. Thank you for the quick response and for the updated code!

**Comment by galets** [comment]
Fix pushed to master
